export const WarrantyCategoryFilterOption = [
  { label: "Monitor", value: "monitor" },
  { label: "Router", value: "router" },
  { label: "Motherboard", value: "motherboard" },
  { label: "Keyboard", value: "keyboard" },
  { label: "Mouse", value: "mouse" },
  { label: "Graphics Card", value: "graphics_card" },
  { label: "CPU", value: "cpu" },
  { label: "Laptop", value: "laptop" },
  { label: "Printer", value: "printer" },
  { label: "Scanner", value: "scanner" },
  { label: "Speakers", value: "speakers" },
  { label: "Headphones", value: "headphones" },
  { label: "Webcam", value: "webcam" },
  { label: "Tablet", value: "tablet" },
  { label: "Smartphone", value: "smartphone" },
  { label: "Smartwatch", value: "smartwatch" },
  { label: "External Hard Drive", value: "external_hard_drive" },
  { label: "SSD", value: "ssd" },
  { label: "RAM", value: "ram" },
  { label: "Power Supply", value: "power_supply" },
];
