export const orderStatus = [
  { id: "1", value: "Received" },
  { id: "2", value: "QC" },
  { id: "3", value: "QC Ok" },
  { id: "4", value: "Engineer Is working" },
  { id: "5", value: "Repair Difficulty" },
  { id: "6", value: "Leak material" },
  { id: "7", value: "Buffer" },
  { id: "8", value: "Repaired" },
  { id: "9", value: "QC Failed" },
  { id: "10", value: "Cancel" },
  { id: "11", value: "Reject" },
  { id: "12", value: "CN" },
  { id: "13", value: "CID" },
  { id: "14", value: "NTF" },
  { id: "15", value: "Required Parts" },
  { id: "16", value: "Not Repairable" },
  { id: "17", value: "Return to Qc library" },
  { id: "18", value: "Return to Qa library" },
  { id: "19", value: "Return to engineer" },
  { id: "20", value: "Return to library" },
  { id: "21", value: "QA" },
  { id: "22", value: "QA Ok" },
  { id: "23", value: "Completed" },
  { id: "24", value: "Delivered" },
];
